// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBQubcCrrsjW6UpkevxFFenPWFRGaH7rg',
    appId: '1:886470952306:web:09e43f10f1a09803a309eb',
    messagingSenderId: '886470952306',
    projectId: 'travel-app2-4235b',
    authDomain: 'travel-app2-4235b.firebaseapp.com',
    storageBucket: 'travel-app2-4235b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHDsiKwfag4rMByYvHqtc2zSrdQgPrccE',
    appId: '1:886470952306:android:a8d839e6c1a0200aa309eb',
    messagingSenderId: '886470952306',
    projectId: 'travel-app2-4235b',
    storageBucket: 'travel-app2-4235b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Cl_gfZzdWsydrkDpyOvIG_BSUUqZOrM',
    appId: '1:886470952306:ios:45a0536b2f54741ba309eb',
    messagingSenderId: '886470952306',
    projectId: 'travel-app2-4235b',
    storageBucket: 'travel-app2-4235b.appspot.com',
    iosBundleId: 'com.example.personalTravelGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Cl_gfZzdWsydrkDpyOvIG_BSUUqZOrM',
    appId: '1:886470952306:ios:45a0536b2f54741ba309eb',
    messagingSenderId: '886470952306',
    projectId: 'travel-app2-4235b',
    storageBucket: 'travel-app2-4235b.appspot.com',
    iosBundleId: 'com.example.personalTravelGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBQubcCrrsjW6UpkevxFFenPWFRGaH7rg',
    appId: '1:886470952306:web:4e167b7869c67133a309eb',
    messagingSenderId: '886470952306',
    projectId: 'travel-app2-4235b',
    authDomain: 'travel-app2-4235b.firebaseapp.com',
    storageBucket: 'travel-app2-4235b.appspot.com',
  );
}
